services:
  mosquitto:
    image: "eclipse-mosquitto:latest" #Usamos la imagen oficial de MQTT,
    ports:
      - "1883:1883" #La inicializamos y exponemos el puerto 1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  sensor:
    build: #Crea la imagen usando el dockerfile
      context: ./sensor
      dockerfile: Dockerfile.sensor
    depends_on: #Se asegura de que mosquitto este listo antes de arrancar
      - mosquitto
    volumes:
      - ./sensor/logs:/app/logs  
      - ./sensor/data:/app/data   

  consumidor:
    build:
      context: ./consumidor
      dockerfile: Dockerfile.consumidor
    depends_on:
      - mosquitto
    volumes:
      - ./consumidor/logs:/app/logs   
      - ./consumidor/data:/app/data   
