name: Python MQTT Prototipo

# Se ejecuta en cada push o pull request a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el repositorio
    - uses: actions/checkout@v5

    # 2️⃣ Instalar Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3️⃣ Instalar dependencias necesarias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paho-mqtt

    # 4️⃣ Opcional: verificar que los scripts se ejecutan (sin broker real)
    - name: Test consumer script
      run: python consumidor/consumidor.py --dry-run || true

    - name: Test sensor script
      run: python sensor/sensor.py --dry-run || true
